# cPanel Git deployment configuration for Great Owl Marketing
# Repo: detect2173/GreatOwlSite
# cPanel user: greagfup
# Live document root: /home/greagfup/public_html/

deployment:
  tasks:
    - export DEPLOYPATH=/home/greagfup/public_html/
    - echo "Starting deployment to $DEPLOYPATH at $(date)"
    # Ensure target directory exists
    - mkdir -p $DEPLOYPATH
    # Preferred: rsync is typically available on Namecheap cPanel servers
    # Preserve .well-known and cgi-bin directories
    - /bin/rsync -avz --delete --exclude ".git" --exclude ".cpanel" --exclude ".well-known" --exclude "cgi-bin" ./ $DEPLOYPATH
    - echo "Deployment completed at $(date)"
