name: Deploy to hosting via SFTP

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # If you later add a build step (e.g., bundling), place it here.
      # - name: Build
      #   run: |
      #     npm ci
      #     npm run build

      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SFTP_HOST }}
          port: ${{ secrets.SFTP_PORT }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASSWORD }}
          local_path: ./
          remote_path: ${{ secrets.REMOTE_PATH }}
          sftp_only: true
          exclude: |
            .git*
            .github/**
            node_modules/**
            README.md
